auth:
  type: DISABLED
kafka:
  clusters:
  - bootstrapServers: kafka:9092
    consumerProperties: {}
    kafkaConnect: []
    masking: []
    name: local
    producerProperties: {}
    properties: {}
    readOnly: false
    serde: []
rbac:
  roles: []
webclient: {}
