#ghcr.io
ARG DOCKER_REGISTRY_URL=ghcr.registry.cyou
ARG KAFKA_UI_VERSION=latest
FROM ${DOCKER_REGISTRY_URL}/kafbat/kafka-ui:${KAFKA_UI_VERSION}

LABEL maintainer="zz <373045134@qq.com>"

ENV TZ=Asia/Shanghai
